---
- name: mobilizon role
  tags: [role-mobilizon]
  block:

  # install
  - ansible.builtin.import_tasks: mobilizon-install.yml

  # config
  - ansible.builtin.import_tasks: mobilizon-config.yml

  # service
  - ansible.builtin.import_tasks: mobilizon-service.yml