---
- name: mobilizon role
  tags:
    - mobilizon
  block:

  # install
  - ansible.builtin.import_tasks: install.yml

  # config
  - ansible.builtin.import_tasks: config.yml

  # database
  - ansible.builtin.import_tasks: database.yml

  # service
  - ansible.builtin.import_tasks: service.yml

  # certbot
  - ansible.builtin.import_tasks: certbot.yml
  
  # nginx
  - ansible.builtin.import_tasks: nginx.yml