---
- name: mobilizon role
  tags:
    - mobilizon
  block:

  # install
  - ansible.builtin.import_tasks: mobilizon-install.yml

  # config
  - ansible.builtin.import_tasks: mobilizon-config.yml

  # database
  - ansible.builtin.import_tasks: mobilizon-database.yml

  # service
  - ansible.builtin.import_tasks: mobilizon-service.yml
  
  # nginx
  - ansible.builtin.import_tasks: mobilizon-nginx.yml

  # certbot
  # - ansible.builtin.import_tasks: mobilizon-certbot-nginx.yml