---
- tags: mobilizon-nginx
  block:

  # assert
  - name: Assertions
    ansible.builtin.assert:
      that:
      - mobilizon_config_domain != None
      - mobilizon_nginx_ssl_pub != None
      - mobilizon_nginx_ssl_key != None

  # check if nginx is installed
  - when: mobilizon_nginx_install == false
    block:

    - name: Check if nginx is installed
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.command: dpkg-query -l "nginx"
      register: __mobilizon_nginx_package_check

    # assert
    - name: Assertions
      ansible.builtin.assert:
        that:
        - mobilizon_config_domain != None
        - __mobilizon_nginx_package_check is succeeded

  # install
  - name: Install nginx
    when: mobilizon_nginx_install == true
    delegate_to: "{{ mobilizon_nginx_host }}"
    become: true
    ansible.builtin.apt:
      state: present
      name: nginx

  # template
  - name: Template /etc/nginx/sites-available/mobilizon.conf
    become: true
    delegate_to: "{{ mobilizon_nginx_host }}"
    ansible.builtin.template:
      src: "{{ mobilizon_nginx_template }}"
      dest: /etc/nginx/sites-available/mobilizon.conf
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    notify: systemctl reload nginx

  # link
  - name: Create link at /etc/nginx/sites-enabled/mobilizon.conf
    become: true
    delegate_to: "{{ mobilizon_nginx_host }}"
    ansible.builtin.file:
      src: /etc/nginx/sites-available/mobilizon.conf
      dest: /etc/nginx/sites-enabled/mobilizon.conf
      state: link
    notify: systemctl reload nginx