---
- tags: [role-mobilizon-config]
  block:

  # assert
  - name: Assertions for mariadb role
    ansible.builtin.assert:
      that:
      - mobilizon_config_mail_to != None
      - mobilizon_config_mail_server != None
      - mobilizon_config_mail_hostname != None
      - mobilizon_config_mail_port != None
      - mobilizon_config_mail_username != None
      - mobilizon_config_mail_password != None
      - mobilizon_config_secret_key_base != None
      - mobilizon_config_secret_key != None
      - mobilizon_config_domain != None
      quiet: true

  # template
  - name: Template config file config.exs.j2
    ansible.builtin.template:
      src: config.exs.j2
      dest: "{{ mobilizon_dir_config }}/config.exs"
      owner: mobilizon
      group: mobilizon
      mode: u=rw,g=,o=