---
# postgresql
- name: systemctl restart postgresql.service
  ansible.builtin.systemd_service:
    name: postgresql.service
    state: restarted

- name: systemctl reload postgresql.service
  ansible.builtin.systemd_service:
    name: postgresql.service
    state: reloaded

# mobilizon
- name: systemctl restart mobilizon.service
  ansible.builtin.systemd_service:
    name: mobilizon.service
    state: restarted

# daemon
- name: systemctl daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true